config/routes.rb
DeviseExample::Application.routes.draw do
  root 'home#index'
  devise_for :users
  devise_scope :user do
    get "sign_up", to: "devise/registrations#new"
    get "sign_in", to: "devise/sessions#new"
  end
  resources :users do
    member do
      get "profile"
    end
    collection do
      get :search_auto
    end
    resources :albums do
      resources :images do
        resources :comment_images
      end
    end
    resources :activities
 	  resources :friendships
 	  resources :groups
 	  resources :statuses do
      resources :comments
      resources :shares
    end
  end
  resources :like_statuses do
    collection do
      get :like_or_unlike
    end
  end
  resources :like_comments do
    collection do
      get :like_or_unlike
    end
  end
end

app/models/group.rb
class Group < ActiveRecord::Base
	has_many :users, through: :memberships
	has_many :memberships
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
	def index
		@user = User.find params[:id]
	end

  def show
  	@user = User.find params[:user_id]
  	@group = @user.groups.find params[:id]
  end

  def new
  	@group = Group.new
  end

  def create
  	@group = Group.new params.require(:group).permit :name
  	if @group.save
  		@group.update_attribute(:user_id, current_user.id)
  		Membership.create!(user_id: current_user.id, group_id: @group.id )
  	end
  	redirect_to user_path(current_user)
  end
end

app/views/groups/_index.html.erb
<% provide(:title, "All group") %>
<% if @user %>
  <h4>groups(<%= @user.groups.count %>)</h4>
  <% @user.groups.each do |group| %>
    <li><%= link_to group.name, user_group_path(@user, group) %></li>
  <% end %>
<% else %>
  <h4>groups(<%= current_user.groups.count %>)</h4>
  <% current_user.groups.each do |group| %>
    <li><%= link_to group.name, user_group_path(current_user, group) %></li>
  <% end %>
<% end %>

app/views/groups/new.html.erb
<%= form_for [current_user, @group] do |f| %>
  <div class="stt_area">
    <%= f.text_field :name %>
  </div>
	<div><%= f.submit "Create Group" %></div>
<% end %>

app/views/groups/show.html.erb
<%= @group.name %>