config/routes.rb
DeviseExample::Application.routes.draw do
  root 'home#index'
  devise_for :users
  devise_scope :user do
    get "sign_up", to: "devise/registrations#new"
    get "sign_in", to: "devise/sessions#new"
  end
  resources :users do
    member do
      get "profile"
    end
    collection do
      get :search_auto
    end
    resources :albums do
      resources :images do
        resources :comment_images
      end
    end
    resources :activities
 	  resources :friendships
 	  resources :groups
 	  resources :statuses do
      resources :comments
      resources :shares
    end
  end
  resources :like_statuses do
    collection do
      get :like_or_unlike
    end
  end
  resources :like_comments do
    collection do
      get :like_or_unlike
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, 
  	:trackable, :validatable, :token_authenticatable, :lockable
  has_many :friendships, dependent: :destroy
  has_many :friend_users, through: :friendships, source: :friended
  has_many :reverse_friendships, foreign_key: "friend_id",
    class_name: "Friendship", dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :groups, dependent: :destroy
  has_many :statuses, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :like_statuses, dependent: :destroy
  has_many :liked_statuses, through: :like_statuses, source: :status
  has_many :like_comments, dependent: :destroy
  has_many :shares, dependent: :destroy
  has_many :share_statuses, through: :shares, dependent: :destroy, source: :status
  has_many :liked_comments, through: :like_comments, source: :comment
  has_many :albums, dependent: :destroy
  has_many :images, dependent: :destroy
  has_many :comment_images, dependent: :destroy
  mount_uploader :avatar, ImageUploader
  mount_uploader :cover, ImageUploader
  validates :gender, presence: true
  validates :name, presence: true
  def friended? other_user
    friendships.find_by friend_id: other_user.id
  end

  def add_friend! other_user
    friendships.create! friend_id: other_user.id
  end

  def unfriend! other_user
    if friendships.find_by(friend_id: other_user.id)
      friendships.find_by(friend_id: other_user.id).destroy!
    end
  end

  def get_permit string
    case string
    when "public"
      self.update_attributes permit: Settings.permit.public
    when "friend"
      self.update_attributes permit: Settings.permit.friend
    when "private"
      self.update_attributes permit: Settings.permit.private
    end
  end

  def public?
    permit == Settings.permit.public
  end

  def private?
    permit == Settings.permit.private
  end

  def friend?
    permit == Settings.permit.friend
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper

	before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]
  def show
  	@user = User.find params[:id]
    @statuses = Status.all
  	@status = Status.new
  	@group  = Group.new
  	@user_friendship = current_user.friendships
  	@user_friend = @user_friendship.find_by friend_id: @user
    @comment = Comment.new
  end

  def edit
  end

  def search_auto
    if params[:name].present?
      users = User.where("name LIKE ?", "%#{params[:name]}%").limit(4)
      if users
        data = users.map{|u| {name: u.name, id: u.id} }
        render json: data
      else
        render nothing:true
      end
    end
  end

  def update
    if params[:flag]
      current_user.get_permit params[:flag]
    else
      current_user.update_attributes user_params
    end
    Activity.user_edit_profile! current_user
    redirect_to user_path current_user
  end

  def profile
    @user = User.find params[:id]
  end

  private
  def user_params
    params.require(:user).permit :name, :birthday, :gender,
      :status_relationship, :address, :favorite_book, :favorite_quote, :avatar, :cover
  end

  def correct_user
    @user = User.find params[:id]
    redirect_to user_path(current_user) unless current_user?(@user)
  end 
end

app/views/users/_add_friend.html.erb
<%= form_for [current_user, @user_friendship.build(friend_id: @user.id)] do |f| %>
  <%= f.hidden_field :friend_id %>
  <%= f.submit "Add Friend", class: "btn btn-large btn-primary" %>
<% end %>

app/views/users/_condition_fields.html.erb
<div>
  <input type= "text" id="autocomplete_input" placeholder="Search friends..." />
</div>
<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css">
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
<script>
	$("#autocomplete_input").autocomplete({
		source: function( request, response ) {
		$.ajax({
		  url: "/users/search_auto",
		    data: {
		      name: request.term
		    },
		  success: function( data ) {
		    response( $.map( data, function( item ) {
		      return {
		        label: item.id,
		        value: item.name
		      }
		    }));
		  }
		});
	},
	minLength: 2,
		select: function( event, ui ) {
		}
	}).data( "ui-autocomplete" )._renderItem = function(ul,item){
    return $("<li>")
      .append("<a href='/users/"+ item.label+"'>" + item.value + "</a>")
      .appendTo(ul);
  };	
</script>

app/views/users/_friend_form.html.erb
<% unless current_user? @user %>
  <% if current_user.friended? @user %>
    <%= render "unfriend" %>
  <% else %>
    <%= render "add_friend" %>
  <% end %>
<% end %>

app/views/users/_info_user.html.erb
<% if @user.avatar? %>
  <div class="avatar">
    <%= image_tag @user.avatar, id: "avatar", title: 'Click to change avatar', rel: 'tooltip' %>
  </div>
<% else %>
  <%= image_tag "https://fbcdn-profile-a.akamaihd.net/hprofile-ak-frc1/c178.0.604.604/s160x160/252231_1002029915278_1941483569_n.jpg", id: "avatar", title: 'Click to change avatar', rel: 'tooltip' %>
<% end %>
<% if current_user? @user %>
  <%= form_for current_user, :html => { :multipart => true } do |f| %>
  <%= f.file_field :avatar, id: "btn_change_avatar" , style: "display: none", accept: "image/*" %>
  <% end %>
  <%= link_to "Edit profile", edit_user_path(current_user) %>
<% end %>
<ul>
  <li>Name: <a><%= @user.name %></a></li>
  <li>Email: <a><%= @user.email %></a></li>
  <li>Birthday: <a><%= I18n.l @user.birthday %></a></li>
  <li>Gender: <a><%= @user.gender %></a></li>
</ul>

app/views/users/_show_activities.html.erb
<ul>
	<% Activity.all.order_desc_created_at.each do |activity| %>
	  <% if activity.user.friended? current_user %>
		  <div class="activities">
		  	<%= link_to small_avatar(activity.user), activity.user %>
		  	<li class="activities_content">
			  	<% case activity.temtype %>
			  	<% when "EDIT_PROFILE" %>
			  		<%= link_to activity.user.name, activity.user %> was updated profile
			  	<% when "POST_STATUS" %>
			  		<%= link_to activity.user.name, activity.user %> posted a status in <%= link_to activity.effect_user.name, activity.effect_user %> wall
			  	<% when "COMMENT_STATUS" %>
			  		<%= link_to activity.user.name, activity.user %> commented in a status of <%= link_to activity.effect_user.name, activity.effect_user %>
			  	<% when "ADD_FRIEND" %>
			  		<%= link_to activity.user.name, activity.user %> added friend with <%= link_to activity.effect_user.name, activity.effect_user %>
			  	<% when "LIKE__STATUS" %>
			  		<%= link_to activity.user.name, activity.user %> liked a status of <%= link_to activity.effect_user.name, activity.effect_user %>
			  	<% when "SHARE__STATUS" %>
			  		<%= link_to activity.user.name, activity.user %> shared a status of <%= link_to activity.effect_user.name, activity.effect_user %>
					<% end %>
			 		<%= time_ago_in_words activity.created_at %> ago
			 	</li>
		 </div>
		<% end %>
	<% end %>
</ul>

app/views/users/_status_comments.html.erb
<div class="status-user">
  <% if status.create_by_friend? %>
    <div class="status-image">
      <%= link_to gravatar_for(status.user), status.user %>
    </div>
    <%= link_to status.status_host.name, status.status_host %> to <%= link_to status.user.name, status.user %> <br/>
    <%= status.content.html_safe %>
  <% else %>
  <div class="status-image">
    <%= link_to gravatar_for(status.user), status.user %>
  </div>
  <div class="status-content-wrap">
    <div class="name">          
      <%= link_to status.user.name, status.user %> </br>
    </div>
    <div class="status-content">
      <%= status.content.html_safe %>
    </div>
  </div>
  <% end %>
  <div class="status-meta" >
    <% if current_user.id == status.host_id && current_user?(@user) %>
      <li class="dropdown">
        <a href="#" data-toggle="dropdown" class="dropdown-toggle">policy<b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to "public", user_status_path(@user, status, flag: "public"), method: :patch %></li>
          <li><%= link_to "friend", user_status_path(@user, status, flag: "friend"), method: :patch %></li>
          <li><%= link_to "private", user_status_path(@user, status, flag: "private"), method: :patch %></li>
        </ul>
      </li>
    <% end %>
    <%= time_ago_in_words status.created_at %> ago
    <a class= "like_status_btn btn_<%= status.id %>" data-id="<%= current_user.id %>" data-status="<%= status.id %>">
      <% if status.liked? current_user %>
        Unlike
      <% else %>
        Like
      <% end %>
     </a>
    <span class="num"><%= status.like_statuses.count if status.like_statuses.count > 0  %></span>
    <%= link_to "share", user_status_shares_path(current_user, status), method: :post, confirm: "Do you want share this status in your wall?" %> 
    <%= status.share_by_users.count if status.share_by_users.count > 0 %>
    <% if status.shared_by?(current_user) && current_user?(@user) %>
      <%= link_to "delete", user_status_share_path(current_user, status, current_user.shares.shared(status.id).first), method: :delete %> 
    <% end %>
    <% if status.user_id == current_user.id %>
        <%= link_to "edit", "#", class: "non-redirect edit-status-btn" %>        
        <%= link_to "delete", user_status_path(@user, status), method: :delete, confirm: "Are you sure?" %>
    <% end %>
  </div>
  <div class="edit-status-wrap" style="display: none" >
      <%= form_for [current_user, status] do |f| %>
        <%= f.text_area :content %>
        <%= f.submit "Edit status" %>
      <% end %>
    </div>
  <div class="status-comments">
    <% status.comments.each do |comment| %>
      <div class="status-comment">
        <div class="name">
          <%= link_to small_avatar(comment.user), comment.user %>
          <%= link_to comment.user.name, comment.user %>
        </div>
        <%= comment.content %></br>
        <%= time_ago_in_words(comment.created_at) %> ago
        <a class= "like_comment_btn btn_<%= comment.id %>" data-id="<%= current_user.id %>" data-comment="<%= comment.id %>">
          <% if comment.liked_by? current_user %>
            Unlike
          <% else %>
            Like
          <% end %>
        </a>
        <span class="number"><%= comment.like_comments.count if comment.like_comments.count > 0  %></span>
        <% if status.user_id == current_user.id || comment.user_id == current_user.id %>
          <%= link_to "edit", "#", class: "non-redirect edit_comment_btn" %>
          <%= link_to "delete", user_status_comment_path(@user, status, comment), method: :delete, confirm: "Are you sure?" %> 
        <% end %>
      </div>
      <div class="edit_comment_wrap" style="display: none" >
        <%= form_for [current_user, status, comment] do |f| %>
          <%= f.text_area :content, class: "edit-comment-status", onkeyup:"textAreaAdjust(this)" %>
        <% end %>
      </div>
    <% end %>
    <%= form_for [current_user, status, @comment] do |f|%>
      <div class="comment">
        <%= f.text_area :content, placeholder:"Write comment...", class: "comment_status", onkeyup:"textAreaAdjust(this)" %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_unfriend.html.erb
<%= form_for [current_user, @user_friend], html: { method: :delete } do |f| %>
	<% if @user.friended? current_user %>
  	<%= f.submit "Unfriend", class: "btn btn-large" %>
  <% else %>
  	<%= f.submit "Destroy invite friend!", class: "btn btn-large" %>
  <% end %>
<% end %>

app/views/users/edit.html.erb
<div class="edit_profile">
  <h3>Change Users Profile</h3>
  <%= form_for current_user do |f| %>
    <%= render 'shared/error_messages' %>
    <%= f.label :name %>
    <div class="input_new"><%= f.text_field :name %></div>
    <%= f.label :birthday %>
    <div class="date_select">
      <%= f.date_select :birthday, order: [:day, :month, :year] %>
    </div>
    <%= f.radio_button :gender, "male" %> Male
    <%= f.radio_button :gender, "female" %> Female<br>

    <%= f.label :status_relationship %>
    <%= f.text_area :status_relationship %>

    <%= f.label :address %>
    <%= f.text_area :address %>

    <%= f.label :favorite_book %>
    <%= f.text_area :favorite_book %>

    <%= f.label :favorite_quote %>
    <%= f.text_area :favorite_quote %>

    <div><%= f.submit "Update" %></div>
  <% end %>
  <%= link_to "Cancel", :back %>
</div>

app/views/users/profile.html.erb
<% if current_user?(@user) || @user.public? || (current_user.friended?(@user) && @user.friend?) %>
  <div class="status_content" >  
    <ul>
      <li>Name: <a><%= @user.name %></a></li>
      <li>Email: <a><%= @user.email %></a></li>
      <li>Birthday: <a><%= I18n.l @user.birthday %></a></li>
      <li>Gender: <a><%= @user.gender %></a></li>
      <% if @user.status_relationship.present? %>
        <li>User status relationship: <a><%= @user.status_relationship %></a></li>
      <% end %>
      <% if @user.address.present? %>
        <a><li>User address: <%= @user.address %></a></li>
      <% end %>
      <% if @user.favorite_book.present? %>
        <a><li>User favorite book: <%= @user.favorite_book %></a></li>
      <% end %>
      <% if @user.favorite_quote.present? %>
        <a><li>User favorite quote: <%= @user.favorite_quote %></a></li>
      <% end %>
    </ul>
  </div>
  <% else %>
  <h4>This information is private!</h4>
<% end %>

app/views/users/show.html.erb
<div class="menu_user">
  <li><%= link_to "Friends", user_friendships_path(@user) %><%= @user.friendships.count %></li>
  <li><%= link_to "View profile", profile_user_path(@user) %></li> 
  <li><%= link_to "Albums", user_albums_path(@user) %>
  <% if @user.albums.count > 0 %>
    (<%= @user.albums.count %>)</br>
  <% end %></li>
</div>
<div>
  <%= render "friend_form" if signed_in? %>
</div>
<% if current_user.friended?(@user) || current_user?(@user) %>
  <%= render "statuses/new" %>
<% end %>
<% @statuses.order_desc_created_at.each do |status| %>
  <% if status.shared_by?(@user) || status.concern?(@user) %>
    <% if current_user?(@user) || (current_user.friended?(@user) && status.friend?) || status.public? %>
      <%= render "status_comments", status: status %>
    <% end %>
  <% end %>
<% end %>