config/routes.rb
DeviseExample::Application.routes.draw do
  root 'home#index'
  devise_for :users
  devise_scope :user do
    get "sign_up", to: "devise/registrations#new"
    get "sign_in", to: "devise/sessions#new"
  end
  resources :users do
    member do
      get "profile"
    end
    collection do
      get :search_auto
    end
    resources :albums do
      resources :images do
        resources :comment_images
      end
    end
    resources :activities
 	  resources :friendships
 	  resources :groups
 	  resources :statuses do
      resources :comments
      resources :shares
    end
  end
  resources :like_statuses do
    collection do
      get :like_or_unlike
    end
  end
  resources :like_comments do
    collection do
      get :like_or_unlike
    end
  end
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friended, foreign_key: "friend_id", class_name: "User" 
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = User.find params[:user_id]
    @users = User.all
    @user_friendship = current_user.friendships
  end

  def create
    @user = User.find params[:friendship][:friend_id]
    current_user.add_friend! @user
    Activity.add_friend! current_user, @user
    redirect_to :back
  end

  def destroy
    @user = Friendship.find(params[:id]).friended
    current_user.unfriend! @user
    @user.unfriend! current_user
    redirect_to :back
  end

  private
  def load_object
  end
end

app/views/friendships/_invite_friend.html.erb
<h3> All invite friend </h3>
<% @users.each do |user| %>
	<% if user.friended?(current_user) && !current_user.friended?(user) %>
    <div class="status-image">
      <%= link_to gravatar_for(user), user %>
    </div>
		<%= link_to user.name, user %>
		<%= form_for [current_user, @user_friendship.build(friend_id: user.id)] do |f| %>
		  <%= f.hidden_field :friend_id %>
      <%= f.submit "accept invite", class: "btn btn-tiny btn-primary" %>
		<% end %>
	<% end %>
<% end %>

app/views/friendships/index.html.erb
<% provide(:title, "All friend") %>
<h3>All friends (<%= @user.friendships.count %>)</h3>

<% @user.friendships.each do |friendship| %>
  <div>
    <%= link_to gravatar_for(friendship.friended), friendship.friended %>
    <%= link_to friendship.friended.name, friendship.friended %>
    <%= link_to "Unfriend", user_friendship_path(current_user, friendship.friended), method: :delete, confirm: "Are you sure?"%>
  </div>
<% end %>
<%= render "invite_friend" %>