config/routes.rb
DeviseExample::Application.routes.draw do
  root 'home#index'
  devise_for :users
  devise_scope :user do
    get "sign_up", to: "devise/registrations#new"
    get "sign_in", to: "devise/sessions#new"
  end
  resources :users do
    member do
      get "profile"
    end
    collection do
      get :search_auto
    end
    resources :albums do
      resources :images do
        resources :comment_images
      end
    end
    resources :activities
 	  resources :friendships
 	  resources :groups
 	  resources :statuses do
      resources :comments
      resources :shares
    end
  end
  resources :like_statuses do
    collection do
      get :like_or_unlike
    end
  end
  resources :like_comments do
    collection do
      get :like_or_unlike
    end
  end
end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :images
  belongs_to :user
  validates :title, presence: true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user! 
  def index
    @user = User.find params[:user_id]
    @album = current_user.albums.new
  end

  def show
    @user = User.find params[:user_id]
    @album = Album.find params[:id]
    @image = Image.new
  end

  def new
    @album = Album.new
  end

  def create
    if params[:album][:title].present?
      @album = Album.new(params_album)
      @album.update_attribute(:user_id, params[:user_id])
      if @album.save
        flash[:success] = "Created album"
      end
    end
    redirect_to :back
  end

  def destroy
    @album = Album.find params[:id]
    @album.destroy
    redirect_to :back
  end
  private 
  def params_album
    params.require(:album).permit :title, :description
  end
end

app/views/albums/_new.html.erb
<%= form_for [current_user, @album] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit "Create" %>
<% end %>

app/views/albums/index.html.erb
<% if current_user? @user %>
<h3>Create Album</h3>
  <%= render"new" %>
<% end %>
<% @user.albums.each do |album| %>
  <li>
    <div class="album_all">
      <%= link_to album.title, user_album_path(@user, album) %> (<%= album.images.count %>)
      <%= link_to image_tag("https://cdn1.iconfinder.com/data/icons/softwaredemo/PNG/256x256/DeleteRed.png") , user_album_path(current_user, album), method: :delete, confirm: "Are you sure?" if current_user? @user %>
    </div>
  </li>
<% end %>

app/views/albums/show.html.erb
<div class="album">
  <h3> All images </h3>
  <% @album.images.each do |image| %>
    <%= link_to image_tag(image.photo), user_album_image_path(@user, @album, image), html_options = {class: "fancybox", rel:"image"} %>
    <%= link_to image_tag("https://cdn1.iconfinder.com/data/icons/softwaredemo/PNG/256x256/DeleteRed.png"), user_album_image_path(current_user, @album, image), method: :delete, confirm:"Are you sure?", class:"button-delete" if current_user? @user %>
  <% end %>
  <% if current_user? @user %>
    <%= render "images/new" %>
  <% end %>
</div>